theme: jekyll-theme-cayman
title:  Future directions: Mathematical Science Community and GCRF initiatives:
description:  Future directions: Mathematical Science Community and GCRF initiatives:
tagline:  Future directions: Mathematical Science Community and GCRF initiatives:
logo: "logo3.png"
